name: e2e test setup-melange

on: push

jobs:
  build:
    name: Build melange package
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@main
      - uses: chainguard-dev/actions/melange-build@main
        with:
          sign-with-temporary-key: true
      - uses: chainguard-dev/actions/apko-build@feature/apko-build-keyring-append
        with:
          tag: ghcr.io/${{ github.repository }}:latest
          keyring-append: /github/workspace/melange.rsa.pub
          archs: x86_64
