name: e2e test setup-melange

on: push

jobs:
  build:
    name: Build melange package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: chainguard-dev/actions/melange-build@feature/melange-build
        with:
          sign-with-temporary-key: true

